# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: POSM admin
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The core of POSM Admin is a suite of bash scripts that do the administrative
  tasks handling data deployment, operation, and backup of the POSM Server.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

destination: "../pages"

# Build settings
markdown: kramdown
